name: docker
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Read Version file
      id: get-version
      run: echo "::set-output name=version::$(cat VERSION)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        # build-args: |
        #   NGINX_PORT=5000
        #   HUGO_ENV=production
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{needs.lint.outputs.version}}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Inspect
      run: |
        docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{needs.lint.outputs.version}}
