name: docker
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main

env:
  IMAGE_NAME: pygandi

jobs:
  linter:
    strategy:
      matrix:
        python-version: ['3.9']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install modules
        run: |
          python3 -m pip install pipenv wheel
      - name: Install pygandi
        run: |
          python3 setup.py bdist_wheel
      - name: Test pygandi
        run: |
          pipenv install --dev
          pipenv run PYTHONPATH=./src pytest

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Read Version file
      id: get-version
      run: echo "{version}=$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker-build
      uses: docker/build-push-action@v3
      with:
        push: true
        build-args: |
          VERSION=${{ steps.get-version.outputs.version }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get-version.outputs.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Image digest
      run: echo ${{ steps.docker-build.outputs.digest }}
